name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: compile
      id: compile
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: compile
        setup-command: ''
        command: g++ --std=c++17 Week16Mon.cpp -o Week16Mon
        timeout: 10
        max-score: 10
    - name: Run
      id: run
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Run
        setup-command: ''
        command: "./Week16Mon"
        input: ''
        expected-output: '1 3 4 5 7 9

          '
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILE_RESULTS: "${{steps.compile.outputs.result}}"
        RUN_RESULTS: "${{steps.run.outputs.result}}"
      with:
        runners: compile,run
